### ISSUE TITLE
Add "Implementations" section

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [RocketRace/setver#2]
So I accidentally implemented this in Rust, it's available as a [public library](https://crates.io/crates/setver) and [here on GitHub](https://github.com/kleinesfilmroellchen/rust-setver). How about an "implementations" section if other people have the same genius idea?

PS: I'm using almost all examples from the spec as tests in my implementation, so I'm pretty confident it's compliant.

**Comment by pulustelu** [comment]
> accidentally implemented this in Rust

Carcinization strikes again! 

I will blindly endorse this library because it's written in Rust 🦀🦀🦀🦀

**Comment by pulustelu** [comment]
Done as of 5e96888
